#!/bin/bash

if [[ -d /tmp/dateThangs ]]
then
  touch /tmp/dateThangs/file-$(date +%Y%M%d)
else
  mkdir /tmp/dateThangs
  
fi

#This will create a file with the current date in a subdir of /tmp/. If that subdir does not exist, the script will make it first.
